//
// AnalyticsAggregatedMetricsResponseContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsAggregatedMetricsResponseContext: Codable, Hashable {

    public enum Metric: String, Codable, CaseIterable {
        case play = "play"
        case start = "start"
        case end = "end"
        case impression = "impression"
        case impressionTime = "impression-time"
        case watchTime = "watch-time"
    }
    public enum Aggregation: String, Codable, CaseIterable {
        case count = "count"
        case rate = "rate"
        case total = "total"
        case average = "average"
        case sum = "sum"
    }
    /** Returns the metric you selected. */
    public var metric: Metric?
    /** Returns the aggregation you selected. */
    public var aggregation: Aggregation?
    public var timeframe: AnalyticsAggregatedMetricsResponseContextTimeframe?

    public init(metric: Metric? = nil, aggregation: Aggregation? = nil, timeframe: AnalyticsAggregatedMetricsResponseContextTimeframe? = nil) {
        self.metric = metric
        self.aggregation = aggregation
        self.timeframe = timeframe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metric
        case aggregation
        case timeframe
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(metric, forKey: .metric)
        try container.encodeIfPresent(aggregation, forKey: .aggregation)
        try container.encodeIfPresent(timeframe, forKey: .timeframe)
    }
}

