//
// AnalyticsPlays400Error.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsPlays400Error: Codable, Hashable {

    /** A link to the error documentation. */
    public var type: String?
    /** A description of the error that occurred. */
    public var title: String?
    /** The HTTP status code. */
    public var status: Int?
    /** A solution for the error. */
    public var detail: String?
    /** The name of the parameter that caused the error. */
    public var name: String?

    public init(type: String? = nil, title: String? = nil, status: Int? = nil, detail: String? = nil, name: String? = nil) {
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case title
        case status
        case detail
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

