//
// AnalyticsMetricsOverTimeResponseContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsMetricsOverTimeResponseContext: Codable, Hashable {

    public enum Metric: String, Codable, CaseIterable {
        case play = "play"
        case playRate = "play-rate"
        case start = "start"
        case end = "end"
        case impression = "impression"
    }
    public enum Interval: String, Codable, CaseIterable {
        case hour = "hour"
        case day = "day"
    }
    /** Returns the metric you selected. */
    public var metric: Metric?
    /** Returns the interval you selected. */
    public var interval: Interval?
    public var timeframe: AnalyticsAggregatedMetricsResponseContextTimeframe?

    public init(metric: Metric? = nil, interval: Interval? = nil, timeframe: AnalyticsAggregatedMetricsResponseContextTimeframe? = nil) {
        self.metric = metric
        self.interval = interval
        self.timeframe = timeframe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metric
        case interval
        case timeframe
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(metric, forKey: .metric)
        try container.encodeIfPresent(interval, forKey: .interval)
        try container.encodeIfPresent(timeframe, forKey: .timeframe)
    }
}

