//
// AnalyticsData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsData: Codable, Hashable {

    /** Shows a value for the property you have specified for `dimension` in your request. For example, if you requested `dimension=videoId`, each `value` field in the response returns a different videoId. */
    public var value: String
    /** Shows the number of play events for one specific `value`. */
    public var plays: Int

    public init(value: String, plays: Int) {
        self.value = value
        self.plays = plays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case plays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(plays, forKey: .plays)
    }
}

