//
// AnalyticsMetricsBreakdownResponseContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsMetricsBreakdownResponseContext: Codable, Hashable {

    public enum Metric: String, Codable, CaseIterable {
        case play = "play"
        case playRate = "play-rate"
        case start = "start"
        case end = "end"
        case impression = "impression"
    }
    public enum Breakdown: String, Codable, CaseIterable {
        case mediaId = "media-id"
        case mediaType = "media-type"
        case continent = "continent"
        case country = "country"
        case deviceType = "device-type"
        case operatingSystem = "operating-system"
        case browser = "browser"
    }
    /** Returns the metric you selected. */
    public var metric: Metric?
    /** Returns the dimension you selected. */
    public var breakdown: Breakdown?
    public var timeframe: AnalyticsAggregatedMetricsResponseContextTimeframe?

    public init(metric: Metric? = nil, breakdown: Breakdown? = nil, timeframe: AnalyticsAggregatedMetricsResponseContextTimeframe? = nil) {
        self.metric = metric
        self.breakdown = breakdown
        self.timeframe = timeframe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metric
        case breakdown
        case timeframe
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(metric, forKey: .metric)
        try container.encodeIfPresent(breakdown, forKey: .breakdown)
        try container.encodeIfPresent(timeframe, forKey: .timeframe)
    }
}

