//
// AnalyticsMetricsOverTimeResponseContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsMetricsOverTimeResponseContext: Codable, Hashable {

    public enum Metric: String, Codable, CaseIterable {
        case play = "play"
        case playRate = "play-rate"
        case start = "start"
        case end = "end"
        case impression = "impression"
        case ccvAverage = "ccv-average"
        case ccvPeak = "ccv-peak"
        case uniqueCcvAverage = "unique-ccv-average"
        case uniqueCcvPeak = "unique-ccv-peak"
        case view3 = "view-3"
        case view5 = "view-5"
        case view10 = "view-10"
        case view30 = "view-30"
        case uniqueView = "unique-view"
        case uniqueView3 = "unique-view-3"
        case uniqueView5 = "unique-view-5"
        case uniqueView10 = "unique-view-10"
        case uniqueView30 = "unique-view-30"
    }
    public enum Interval: String, Codable, CaseIterable {
        case minute = "minute"
        case hour = "hour"
        case day = "day"
    }
    /** Returns the metric and relevant parameters you selected. */
    public var metric: Metric?
    /** Returns the interval you selected. */
    public var interval: Interval?
    public var timeframe: AnalyticsAggregatedMetricsResponseContextTimeframe?

    public init(metric: Metric? = nil, interval: Interval? = nil, timeframe: AnalyticsAggregatedMetricsResponseContextTimeframe? = nil) {
        self.metric = metric
        self.interval = interval
        self.timeframe = timeframe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metric
        case interval
        case timeframe
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(metric, forKey: .metric)
        try container.encodeIfPresent(interval, forKey: .interval)
        try container.encodeIfPresent(timeframe, forKey: .timeframe)
    }
}

