//
// AnalyticsAggregatedMetricsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsAggregatedMetricsResponse: Codable, Hashable {

    public var context: AnalyticsAggregatedMetricsResponseContext
    public var data: Float

    public init(context: AnalyticsAggregatedMetricsResponseContext, data: Float) {
        self.context = context
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case context
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(context, forKey: .context)
        try container.encode(data, forKey: .data)
    }
}

