//
// Chapter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Chapter: Codable, Hashable {

    public var uri: String?
    /** The link to your VTT file, which contains your chapters information for the video. */
    public var src: String?
    public var language: String?

    public init(uri: String? = nil, src: String? = nil, language: String? = nil) {
        self.uri = uri
        self.src = src
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uri
        case src
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uri, forKey: .uri)
        try container.encodeIfPresent(src, forKey: .src)
        try container.encodeIfPresent(language, forKey: .language)
    }
}

