//
// DiscardedVideoUpdatePayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DiscardedVideoUpdatePayload: Codable, Hashable {

    /** Use this parameter to restore a discarded video when you have the Video Restore feature enabled. This parameter only accepts `false` as a value! */
    public var discarded: Bool?

    public init(discarded: Bool? = nil) {
        self.discarded = discarded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case discarded
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(discarded, forKey: .discarded)
    }
}

