//
// ListTagsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListTagsResponse: Codable, Hashable {

    public var data: [ListTagsResponseData]?
    public var pagination: Pagination?

    public init(data: [ListTagsResponseData]? = nil, pagination: Pagination? = nil) {
        self.data = data
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

