//
// LiveStreamCreationPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveStreamCreationPayload: Codable, Hashable {

    /** Add a name for your live stream here. */
    public var name: String
    /** Whether you are recording or not. True for record, false for not record. */
    public var record: Bool? = false
    /** Whether your video can be viewed by everyone, or requires authentication to see it. A setting of false will require a unique token for each view. Learn more about the Private Video feature [here](https://docs.api.video/docs/private-videos). */
    public var _public: Bool?
    /** The unique identifier for the player. */
    public var playerId: String?

    public init(name: String, record: Bool? = false, _public: Bool? = nil, playerId: String? = nil) {
        self.name = name
        self.record = record
        self._public = _public
        self.playerId = playerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case record
        case _public = "public"
        case playerId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(record, forKey: .record)
        try container.encodeIfPresent(_public, forKey: ._public)
        try container.encodeIfPresent(playerId, forKey: .playerId)
    }
}

