//
// LiveStreamAssets.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveStreamAssets: Codable, Hashable {

    /** The http live streaming (HLS) link for your live video stream. */
    public var hls: String?
    /** The embed code for the iframe containing your live video stream. */
    public var iframe: String?
    /** A link to the video player that is playing your live stream. */
    public var player: String?
    /** A link to the thumbnail for your video. */
    public var thumbnail: String?

    public init(hls: String? = nil, iframe: String? = nil, player: String? = nil, thumbnail: String? = nil) {
        self.hls = hls
        self.iframe = iframe
        self.player = player
        self.thumbnail = thumbnail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hls
        case iframe
        case player
        case thumbnail
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hls, forKey: .hls)
        try container.encodeIfPresent(iframe, forKey: .iframe)
        try container.encodeIfPresent(player, forKey: .player)
        try container.encodeIfPresent(thumbnail, forKey: .thumbnail)
    }
}

