//
// LiveStreamSessionClient.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** What kind of browser the viewer is using for the live stream session. */
public struct LiveStreamSessionClient: Codable, Hashable {

    /** The name of the browser used to view the live stream session. */
    public var name: String?
    /** The version of the browser used to view the live stream session. */
    public var version: String?
    /** The type of client used to view the live stream session. */
    public var type: String?

    public init(name: String? = nil, version: String? = nil, type: String? = nil) {
        self.name = name
        self.version = version
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case version
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

