//
// LiveStreamSessionSession.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveStreamSessionSession: Codable, Hashable {

    /** A unique identifier for your session. You can use this to track what happens during a specific session. */
    public var sessionId: String?
    /** When the session started, with the date and time presented in ISO-8601 format. */
    public var loadedAt: Date?
    /** When the session ended, with the date and time presented in ISO-8601 format. */
    public var endedAt: Date?

    public init(sessionId: String? = nil, loadedAt: Date? = nil, endedAt: Date? = nil) {
        self.sessionId = sessionId
        self.loadedAt = loadedAt
        self.endedAt = endedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case loadedAt
        case endedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(loadedAt, forKey: .loadedAt)
        try container.encodeIfPresent(endedAt, forKey: .endedAt)
    }
}

