//
// RestreamsRequestObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Adding restream destinations is optional. However, if you set a restream destination, you must provide all attributes for each destination. */
public struct RestreamsRequestObject: Codable, Hashable {

    /** Use this parameter to define a name for the restream destination. */
    public var name: String
    /** Use this parameter to set the RTMP URL of the restream destination. */
    public var serverUrl: String
    /** Use this parameter to provide the unique key of the live stream that you want to restream. */
    public var streamKey: String

    public init(name: String, serverUrl: String, streamKey: String) {
        self.name = name
        self.serverUrl = serverUrl
        self.streamKey = streamKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case serverUrl
        case streamKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(serverUrl, forKey: .serverUrl)
        try container.encode(streamKey, forKey: .streamKey)
    }
}

