//
// RestreamsResponseObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RestreamsResponseObject: Codable, Hashable {

    /** Returns the name of a restream destination. */
    public var name: String?
    /** Returns the RTMP URL of a restream destination. */
    public var serverUrl: String?
    /** Returns the unique key of the live stream that is set up for restreaming. */
    public var streamKey: String?

    public init(name: String? = nil, serverUrl: String? = nil, streamKey: String? = nil) {
        self.name = name
        self.serverUrl = serverUrl
        self.streamKey = streamKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case serverUrl
        case streamKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(serverUrl, forKey: .serverUrl)
        try container.encodeIfPresent(streamKey, forKey: .streamKey)
    }
}

