//
// TokenCreationPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokenCreationPayload: Codable, Hashable {

    /** Time in seconds that the token will be active. A value of 0 means that the token has no exipration date. The default is to have no expiration. */
    public var ttl: Int? = 0

    public init(ttl: Int? = 0) {
        self.ttl = ttl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ttl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ttl, forKey: .ttl)
    }
}

