//
// VideoSessionOs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The operating system the viewer is on. */
public struct VideoSessionOs: Codable, Hashable {

    /** The name of the operating system. */
    public var name: String?
    /** The nickname for the operating system, often representing the version. */
    public var shortname: String?
    /** The version of the operating system. */
    public var version: String?

    public init(name: String? = nil, shortname: String? = nil, version: String? = nil) {
        self.name = name
        self.shortname = shortname
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case shortname
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(shortname, forKey: .shortname)
        try container.encodeIfPresent(version, forKey: .version)
    }
}

