//
// VideoSession.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VideoSession: Codable, Hashable {

    public var session: VideoSessionSession?
    public var location: VideoSessionLocation?
    public var referrer: VideoSessionReferrer?
    public var device: VideoSessionDevice?
    public var os: VideoSessionOs?
    public var client: VideoSessionClient?

    public init(session: VideoSessionSession? = nil, location: VideoSessionLocation? = nil, referrer: VideoSessionReferrer? = nil, device: VideoSessionDevice? = nil, os: VideoSessionOs? = nil, client: VideoSessionClient? = nil) {
        self.session = session
        self.location = location
        self.referrer = referrer
        self.device = device
        self.os = os
        self.client = client
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case session
        case location
        case referrer
        case device
        case os
        case client
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(session, forKey: .session)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(referrer, forKey: .referrer)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(os, forKey: .os)
        try container.encodeIfPresent(client, forKey: .client)
    }
}

