//
// VideoStatusIngestReceivedParts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VideoStatusIngestReceivedParts: Codable, Hashable {

    /** The parts that are have been uploaded, ordered. For example, if part 2 was sent before part 1, and both have been uploaded, the output will be [1, 2]. */
    public var parts: [Int]?
    /** Contains the number of expected parts. The total will be listed as \"null\" until the total number of parts is known. */
    public var total: Int?

    public init(parts: [Int]? = nil, total: Int? = nil) {
        self.parts = parts
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parts
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(parts, forKey: .parts)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

