//
// VideoStatusIngest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Details about the capturing, transferring, and storing of your video for use immediately or in the future. */
public struct VideoStatusIngest: Codable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case uploading = "uploading"
        case uploaded = "uploaded"
        case ingesting = "ingesting"
        case ingested = "ingested"
    }
    /** There are four possible statuses depending on how you provide a video file: - `uploading` - the API is gathering the video source file from an upload. - `uploaded` - the video file is fully uploaded. - `ingesting` - the API is gathering the video source file from either a URL, or from cloning. - `ingested` - the video file is fully stored.  */
    public var status: Status?
    /** The size of your file in bytes. */
    public var filesize: Int?
    /** The total number of bytes received, listed for each chunk of the upload. */
    public var receivedBytes: [BytesRange]?
    public var receivedParts: VideoStatusIngestReceivedParts?

    public init(status: Status? = nil, filesize: Int? = nil, receivedBytes: [BytesRange]? = nil, receivedParts: VideoStatusIngestReceivedParts? = nil) {
        self.status = status
        self.filesize = filesize
        self.receivedBytes = receivedBytes
        self.receivedParts = receivedParts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case filesize
        case receivedBytes
        case receivedParts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(filesize, forKey: .filesize)
        try container.encodeIfPresent(receivedBytes, forKey: .receivedBytes)
        try container.encodeIfPresent(receivedParts, forKey: .receivedParts)
    }
}

