//
// VideoSessionLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The location of the viewer. */
public struct VideoSessionLocation: Codable, Hashable {

    /** The country of the viewer. */
    public var country: String?
    /** The city of the viewer. */
    public var city: String?

    public init(country: String? = nil, city: String? = nil) {
        self.country = country
        self.city = city
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case country
        case city
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(city, forKey: .city)
    }
}

