//
// VideoStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VideoStatus: Codable, Hashable {

    public var ingest: VideoStatusIngest?
    public var encoding: VideoStatusEncoding?

    public init(ingest: VideoStatusIngest? = nil, encoding: VideoStatusEncoding? = nil) {
        self.ingest = ingest
        self.encoding = encoding
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ingest
        case encoding
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ingest, forKey: .ingest)
        try container.encodeIfPresent(encoding, forKey: .encoding)
    }
}

