//
// Webhook.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Webhook: Codable, Hashable {

    /** Unique identifier of the webhook */
    public var webhookId: String?
    /** When an webhook was created, presented in ISO-8601 format. */
    public var createdAt: Date?
    /** A list of events that will trigger the webhook. */
    public var events: [String]?
    /** URL of the webhook */
    public var url: String?

    public init(webhookId: String? = nil, createdAt: Date? = nil, events: [String]? = nil, url: String? = nil) {
        self.webhookId = webhookId
        self.createdAt = createdAt
        self.events = events
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webhookId
        case createdAt
        case events
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(webhookId, forKey: .webhookId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

