//
// SummariesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SummariesAPI {

    /**
     Generate video summary
     
     - parameter inlineObject: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects.
     */
    @discardableResult
    open class func create(inlineObject: InlineObject, apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping ((_ data: SummaryObject?, _ error: Error?) -> Void)) -> RequestTask {
        return create(inlineObject: inlineObject, apiResponseQueue: apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Generate video summary
     
     - parameter inlineObject: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result of the request (incl. headers).
     */
    @discardableResult
    open class func create(inlineObject: InlineObject, apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping (_ result: Swift.Result<Response<SummaryObject>, ErrorResponse>) -> Void) -> RequestTask {
            return createWithRequestBuilder(inlineObject: inlineObject).execute(apiResponseQueue, completion)
    }


    /**
     Generate video summary
     - POST /summaries
     - Generate a title, abstract, and key takeaways for a video.
     - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Retry-After(Int)]
     - parameter inlineObject: (body)  
     - returns: RequestBuilder<SummaryObject> 
     */
    internal class func createWithRequestBuilder(inlineObject: InlineObject) -> RequestBuilder<SummaryObject> {
        let localVariablePath = "/summaries"
        let localVariableURLString = ApiVideoClient.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inlineObject)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SummaryObject>.Type = ApiVideoClient.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }


    /**
     Get summary details
     
     - parameter summaryId: (path) The unique identifier of the summary source you want to retrieve. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects.
     */
    @discardableResult
    open class func get(summaryId: String, apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping ((_ data: SummarySource?, _ error: Error?) -> Void)) -> RequestTask {
        return get(summaryId: summaryId, apiResponseQueue: apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get summary details
     
     - parameter summaryId: (path) The unique identifier of the summary source you want to retrieve. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result of the request (incl. headers).
     */
    @discardableResult
    open class func get(summaryId: String, apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping (_ result: Swift.Result<Response<SummarySource>, ErrorResponse>) -> Void) -> RequestTask {
            return getWithRequestBuilder(summaryId: summaryId).execute(apiResponseQueue, completion)
    }


    /**
     Get summary details
     - GET /summaries/{summaryId}/source
     - Get all details for a summary.
     - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Retry-After(Int)]
     - parameter summaryId: (path) The unique identifier of the summary source you want to retrieve. 
     - returns: RequestBuilder<SummarySource> 
     */
    internal class func getWithRequestBuilder(summaryId: String) -> RequestBuilder<SummarySource> {
        var localVariablePath = "/summaries/{summaryId}/source"
        let summaryIdPreEscape = "\(APIHelper.mapValueToPathItem(summaryId))"
        let summaryIdPostEscape = summaryIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{summaryId}", with: summaryIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ApiVideoClient.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SummarySource>.Type = ApiVideoClient.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }


    /**
     Update summary details
     
     - parameter summaryId: (path) The unique identifier of the summary source you want to update. 
     - parameter updateSummaryRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects.
     */
    @discardableResult
    open class func update(summaryId: String, updateSummaryRequest: UpdateSummaryRequest, apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping ((_ data: SummarySource?, _ error: Error?) -> Void)) -> RequestTask {
        return update(summaryId: summaryId, updateSummaryRequest: updateSummaryRequest, apiResponseQueue: apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update summary details
     
     - parameter summaryId: (path) The unique identifier of the summary source you want to update. 
     - parameter updateSummaryRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result of the request (incl. headers).
     */
    @discardableResult
    open class func update(summaryId: String, updateSummaryRequest: UpdateSummaryRequest, apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping (_ result: Swift.Result<Response<SummarySource>, ErrorResponse>) -> Void) -> RequestTask {
            return updateWithRequestBuilder(summaryId: summaryId, updateSummaryRequest: updateSummaryRequest).execute(apiResponseQueue, completion)
    }


    /**
     Update summary details
     - PATCH /summaries/{summaryId}/source
     - Update details for a summary. Note that this operation is only allowed for summary objects where `sourceStatus` is `missing`.
     - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Retry-After(Int)]
     - parameter summaryId: (path) The unique identifier of the summary source you want to update. 
     - parameter updateSummaryRequest: (body)  
     - returns: RequestBuilder<SummarySource> 
     */
    internal class func updateWithRequestBuilder(summaryId: String, updateSummaryRequest: UpdateSummaryRequest) -> RequestBuilder<SummarySource> {
        var localVariablePath = "/summaries/{summaryId}/source"
        let summaryIdPreEscape = "\(APIHelper.mapValueToPathItem(summaryId))"
        let summaryIdPostEscape = summaryIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{summaryId}", with: summaryIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ApiVideoClient.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateSummaryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SummarySource>.Type = ApiVideoClient.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }


    /**
     Delete video summary
     
     - parameter summaryId: (path) The unique identifier of the summary you want to delete. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects.
     */
    @discardableResult
    open class func delete(summaryId: String, apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return delete(summaryId: summaryId, apiResponseQueue: apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete video summary
     
     - parameter summaryId: (path) The unique identifier of the summary you want to delete. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result of the request (incl. headers).
     */
    @discardableResult
    open class func delete(summaryId: String, apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping (_ result: Swift.Result<Response<Void>, ErrorResponse>) -> Void) -> RequestTask {
            return deleteWithRequestBuilder(summaryId: summaryId).execute(apiResponseQueue, completion)
    }


    /**
     Delete video summary
     - DELETE /summaries/{summaryId}
     - Delete a summary tied to a video.
     - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Retry-After(Int)]
     - parameter summaryId: (path) The unique identifier of the summary you want to delete. 
     - returns: RequestBuilder<Void> 
     */
    internal class func deleteWithRequestBuilder(summaryId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/summaries/{summaryId}"
        let summaryIdPreEscape = "\(APIHelper.mapValueToPathItem(summaryId))"
        let summaryIdPostEscape = summaryIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{summaryId}", with: summaryIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ApiVideoClient.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = ApiVideoClient.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }


    /**
     List summaries
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects.
     */
    @discardableResult
    open class func list(apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping ((_ data: GetSummaries?, _ error: Error?) -> Void)) -> RequestTask {
        return list(, apiResponseQueue: apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List summaries
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result of the request (incl. headers).
     */
    @discardableResult
    open class func list(apiResponseQueue: DispatchQueue = ApiVideoClient.apiResponseQueue, completion: @escaping (_ result: Swift.Result<Response<GetSummaries>, ErrorResponse>) -> Void) -> RequestTask {
            return listWithRequestBuilder().execute(apiResponseQueue, completion)
    }


    /**
     List summaries
     - GET /summaries
     - List all summarries for your videos in a project.
     - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Retry-After(Int)]
     - returns: RequestBuilder<GetSummaries> 
     */
    internal class func listWithRequestBuilder() -> RequestBuilder<GetSummaries> {
        let localVariablePath = "/summaries"
        let localVariableURLString = ApiVideoClient.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSummaries>.Type = ApiVideoClient.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

}
